#!/bin/bash

if [[ ! -e /usr/local/sbin/base ]] || [[ ! -e /usr/local/sbin/menu ]]; then
	exit 1
else
	source /usr/local/sbin/base
fi
OPTIMIZE_FILE="/etc/sysctl.d/custom-optimize.conf"



_credits() {
	cat << END

 This script will not be
 possible without the following:
 
 Bon-chan
 lfasmpao
 PHC_Jayvee
 Min3
 SenseiX

END
	read -n1 -srp " Press enter to end"
	exec "$0"
}


_done() {
	sleep 2
	echo " Done. A system reboot is needed to apply changes"
	read -n1 -srp " Press enter to proceed"
	reboot
}

do_sysctl() {
	cat >> "$OPTIMIZE_FILE" << END
fs.file-max = 51200
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.rmem_default = 65536
net.core.wmem_default = 65536
net.core.netdev_max_backlog = 4096
net.core.somaxconn = 4096
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.ip_local_port_range = 10000 65000
net.ipv4.tcp_max_syn_backlog = 4096
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_window_scaling = 1
END
	[[ ${1} = addBBR ]] && echo -e "\nnet.core.default_qdisc=fq\nnet.ipv4.tcp_congestion_control=bbr" >> "$OPTIMIZE_FILE"
	sysctl -p "$OPTIMIZE_FILE" > /dev/null
}

optim_tcp() {
	if [[ -e "$OPTIMIZE_FILE" ]] || [[ $(cat /proc/sys/net/ipv4/tcp_congestion_control) = bbr ]]; then
		echo -e "\n Already optimized, exiting..."
		sleep 2
		exec "$0"
	else
		echo -e "\n Optimizing, please wait..."
		if [[ $(cat /proc/sys/net/ipv4/tcp_congestion_control) = bbr ]]; then
			do_sysctl
			_done
		else
			if [[ $(find /lib/modules/$(uname -r)/kernel/net/ipv4 -name tcp_bbr* | grep -o bbr) = bbr ]]; then
				do_sysctl "addBBR"
				_done
			else
				do_sysctl
				_done
			fi
		fi
	fi
}


_title2
rm_tmp
cat >> "$tmpfile" << END
Optimize TCP (experimental)
Cmatrix
Uninstall this script
Credits
Exit
END
choices="6"
_enumerate
_prompt
case $opt in
	1)
		optim_tcp
		;;
	2)
		cmatrix -s
		exec "$0"
		;;
	3)
		echo " Coming soon.."
		sleep 2
		exec "$0"
		;;

	4)
		_credits
		;;
	5)
		menu
		;;
esac
